### ISSUE TITLE
Build problem in Ubuntu 15.10

### ISSUE THREAD

**Issue by davidmatas** [macbre/phantomas#584]
I'm having problems installing phantomas in Ubuntu 15.10:

```
37614 verbose stack Error: phantomjs2@2.0.0-alpha install: `node install.js`
37614 verbose stack Exit status 1
37614 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
37614 verbose stack     at emitTwo (events.js:87:13)
37614 verbose stack     at EventEmitter.emit (events.js:172:7)
37614 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
37614 verbose stack     at emitTwo (events.js:87:13)
37614 verbose stack     at ChildProcess.emit (events.js:172:7)
37614 verbose stack     at maybeClose (internal/child_process.js:818:16)
37614 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
37615 verbose pkgid phantomjs2@2.0.0-alpha
```

Any idea?

**Comment by macbre** [comment]
This will be fixed by #488
