### ISSUE TITLE
Install/build error on Ubuntu

### ISSUE THREAD

**Issue by ruandre** [macbre/phantomas#595]
I'm trying to install phantomas via npm on Ubuntu 12.04 LTS but I keep getting the following error:

```
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/phantomas/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/phantomas/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/phantomas/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/phantomas/node_modules/node-sass
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Build failed
/usr/lib
`-- (empty)

npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "phantomas"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/npm-debug.log
npm ERR! code 1
```

Am I missing a dependency related to node-sass, or is it something else?

**Comment by macbre** [comment]
Hard to tell. Can you try `npm install node-sass`?

**Comment by ruandre** [comment]
I tried both `npm install node-sass` and `npm install -g node-sass` before running `npm install -g phantomas` and I still get the same error. Should I post my entire `npm-debug.log` file?

**Comment by macbre** [comment]
It's an issue with compiling phantomas dependency, not the phantomas itself. I believe it's the best to report the issue to `node-sass` directly.

**Comment by ruandre** [comment]
Thanks. I'll report it to `node-sass` and see how that goes.
