### ISSUE TITLE
Single Runs Results in: TypeError: Bad argument

### ISSUE THREAD

**Issue by kidbai** [macbre/phantomas#637]
`phantomas https://github.com/macbre/phantomas --verbose`

Error:

```
internal/child_process.js:278
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at exports.spawn (child_process.js:367:9)
    at engines.run (/Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/lib/engines.js:127:10)
    at phantomas (/Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/lib/index.js:66:16)
    at task (/Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/bin/phantomas.js:145:14)
    at /Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:4819:13
    at replenish (/Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:838:21)
    at /Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:848:15
    at eachOfLimit (/Users/Youngbye/.nvm/versions/v5.11.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:3622:26)
```

Node version is v5.11.0

**Comment by macbre** [comment]
@kidbai, thanks for the bug report. Can you provide the last lines of verbose log that are emitted before this error is reported?

**Comment by kidbai** [comment]
@macbre Error is already complete above.

**Comment by macbre** [comment]
It works for me.

**Comment by xiuhonglee** [comment]
@kidbai Did you solve the problem ?  I confront it twice.  Always bad luck.
