### ISSUE TITLE
Trying to track down error

### ISSUE THREAD

**Issue by RSeidelsohn** [macbre/phantomas#679]
I am still not sure if this rather belongs to https://github.com/stefanjudis/grunt-phantomas from @stefanjudis, so please be indulgent with me.

When I run my **grunt-phantomas** task, I get 
```>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254
>> Phantomas execution not successful -> 254

WRITING RESULT FILES.
>> SOMETHING WENT WRONG...
>> No run was successful.
```

Configuration:
```// phantomas - Collect live statistics using PhantomJS (https://npmjs.org/package/grunt-phantomas)
phantomas: {
    productionSite: {
        options: {
            buildUi   : true,
            assertions: {
                'jsErrors': 0,
            },
            indexPath : './<%= directories.phantomas_dist %>/',
            url       : 'https://www.lesara.de/',
            options: {
                'no-externals'     : true,
                'allow-domain'     : '.cloudfront.net',
                'timeout'          : 60,
                'analyze-css'      : true,
                'film-strip'       : false,
                'ignore-ssl-errors': true,
                'ssl-protocol'     : 'any',
                'verbose'          : true,
                'debug'            : true,
                'engine'           : 'webkit',
                'log': './phantomas.log',
                'web-security'     : false,
            },
        },
    },
},
```
While when I comment out the options.options.allow-domain line, I get this output:

```
Running "phantomas:productionSite" (phantomas) task

PHANTOMAS EXECUTION(S) STARTED.
creating index directory...
>> 5 Phantomas execution(s) done -> checking results:
>> Phantomas execution successful.
>> Phantomas execution successful.
>> Phantomas execution successful.
>> Phantomas execution successful.
>> Phantomas execution successful.

WRITING RESULT FILES.
>> JSON file - phantomas/data/1481786470392.json - written.
>> CSV file - phantomas/data/1481786470392.csv - written.

CHECKING ALL WRITTEN FILES FOR VALID JSON.
Unhandled rejection TypeError: file.match is not a function
    at /home/roman/Development/lesara/node_modules/grunt-phantomas/tasks/lib/phantomas.js:727:23
    at Array.filter (native)
    at null.<anonymous> (/home/roman/Development/lesara/node_modules/grunt-phantomas/tasks/lib/phantomas.js:723:23)
    at null.tryCatcher (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/promise.js:617:18)
    at /home/roman/Development/lesara/node_modules/uncss/node_modules/bluebird/js/release/nodeback.js:45:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I still don't understand why the 'allow-domain' option breaks the run. But anyway I wanted to track down the above issue and it turns out that in the file `./node_modules/grunt-phantomas/tasks/lib/phantomas.js` from line 719 on the code 
```
files = files.filter( function( file ) { 
  return file.match( /\.json/gi );
} ).sort();
``` 
breaks because files looks like this:
```
files:
[ [ '1481726266330.csv',
    '1481726266330.json',
 ...
   '1481786871323.csv',
    '1481786871323.json' ] ]
```
i.e. it contains another array, so that the `match` operator can not be applied because file - which is expected to be a single string instead of an array of string - still looks like that:
```
file:
[ '1481726266330.csv',
  '1481726266330.json',
...
  '1481786871323.csv',
  '1481786871323.json' ]
```
So I simply added the line `files = files[0];` before that code:
```
files = files[0];
files = files.filter( function( file ) {
  return file.match( /\.json/gi );
} ).sort();
```
 and then everything seems to run smotthly, except that no images for the film strip are being created - due to the commented out `allow-domain` entry in combination with `no-externals`. Only if I comment out the whole `options.options` configuration in my Gruntfile.js do I get screenshots, but then I get the `>> Phantomas execution not successful -> 252` error - with code 252 instead of 254.

This whole JS code is way too complicated for me to understand why the files array is nested within another array, thus breaking the creation of the final output and why the `allow-domain` rule (which I set to `.cloudfromt.net`) prevents the whole run.

I would understand if this is too wild for you to take any care of, but if not I would be so happy if this issue could be tracked down and fixed. Something seems to be broken in my installation.

Cheers, Roman.

**Comment by RSeidelsohn** [comment]
Sorry, @macbre , been talking to @stefanjudis and he explained to me that this issue lies rather in his code than in yours, so you're out here. Sorry for the trouble.
