### ISSUE TITLE
Cannot read property 'getEngineArgs' of undefined

### ISSUE THREAD

**Issue by minasm** [macbre/phantomas#718]
Hello @macbre 

Trying to test Phantomas and even though following the instructions I have an error.
Just to make sure cleared all NPM packages and removed node and NPM.

Then did a clean install. However, I keep getting this error once I run this command,

`phantomas https://github.com/macbre/phantomas --verbose
`

```
/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/lib/engines.js:79
		this.options['user-agent'] = "phantomas/" + VERSION + " (" + engine.getUserAgent() + "; " + process.platform + " " + process.arch + ")";

TypeError: Cannot read property 'getEngineArgs' of undefined
    at engines.run (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/lib/engines.js:83:26)
    at phantomas (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/lib/index.js:69:16)
    at task (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/bin/phantomas.js:148:14)
    at /Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:1011:17)
    at /Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:1041:24)
    at /Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:1046:16
    at _parallel (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:3879:5)
    at Object.series (/Users/minasm/.nvm/versions/node/v10.3.0/lib/node_modules/phantomas/node_modules/async/dist/async.js:4735:5)
```
Tried adding `--user-agent` parameter but did not help.
Obviously, I am missing a setting some sort. Any idea how I can sort this out?

Thank you!

**Comment by macbre** [comment]
TravisCI tests fail under Node.js 10.x:

```
$ node --version
v10.3.0
$ npm --version
6.1.0
$ nvm --version
0.33.11
42.35s$ npm ci 
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code ETARGET
npm ERR! notarget No matching version found for phantomjs-prebuilt@2.5.0-dev
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I'll dive deeper into the issue. @minasm - thanks for reporting it!

**Comment by macbre** [comment]
Something is fishy with Node.js 10.x set up by nvm. It works fine for me when using Node.js without a "wrapper".

```
macbre@debian:~/src/git/phantomas$ ./bin/phantomas.js --version
phantomas v1.20.0
macbre@debian:~/src/git/phantomas$ npm -v
6.1.0
macbre@debian:~/src/git/phantomas$ node -v
v10.3.0
```

**Comment by macbre** [comment]
@minasm, I've uploaded a new package to npm called [`phantomjs-prebuilt-macbre`](https://www.npmjs.com/package/phantomjs-prebuilt-macbre) so that npm version (that comes with Node.js 10.x) is able to install it. Previously there was a link to a GitHub tag.

**Comment by macbre** [comment]
@minasm - I've published phantomas v1.20.1 to npm. Can verify if it now works for you?

**Comment by ghost** [comment]
@macbre This version broke our build:

```
[redacted]node_modules\phantomas\lib\engines.js:57
                        throw 'Engine "' + this.options.engine + '" not found!';
                        ^
Engine "webkit" not found!
```

1.20.0 is fine. We're using node node v. 8.x

**Comment by macbre** [comment]
Interesting. Are you using npm version or the git clone?

https://github.com/macbre/phantomas/blob/devel/package.json#L51 - `phantomjs-prebuilt-macbre` npm package needs to be installed now to use PhantomJS 2.5 beta binary.

**Comment by ghost** [comment]
@macbre I'm using the npm version

**Comment by macbre** [comment]
@motherwaym did you run

```
npm install --global --no-optional phantomas phantomjs-prebuilt-macbre
```
?

**Comment by minasm** [comment]
@macbre I did try 
`npm install --global --no-optional phantomas phantomjs-prebuilt-macbre`
However, I am getting an issue. 
`PhantomJS not found on PATH`

Once I download and add the PhantomJS (2.1) I get 
```
Considering PhantomJS found at /usr/local/bin/phantomjs
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.1 @ /usr/local/bin/phantomjs.
Unexpected platform or architecture: darwin/x64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
```

So I remove phantomjs from `/usr/local/bin` and try to install it with

`npm install --global --no-optional phantomas phantomjs-prebuilt-macbre`

 but this fails as well,
```
npm ERR! path /Users/minasmms/.nvm/versions/node/v10.3.0/lib/node_modules/.staging/phantomas-d523be8f/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/minasmms/.nvm/versions/node/v10.3.0/lib/node_modules/.staging/phantomas-d523be8f/node_modules/abbrev' -> '/Users/minasmms/.nvm/versions/node/v10.3.0/lib/node_modules/.staging/abbrev-fc4ef665'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/minasmms/.npm/_logs/2018-06-05T09_36_51_126Z-debug.log
```

I can provide the log if you'd like. Maybe I am missing the something, I tried to follow your guide on [Phantomas](https://github.com/macbre/phantomas)

you have any joy @motherwaym ?
