### ISSUE TITLE
[Phantomas v2] Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#764]
Hi Maciej,

When testing the website `https://www.airfrance.fr/` with phantomas v2 (the node package), I have the following error:

```
Error: Navigation failed because browser has disconnected!
    at /Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:43)
    at CDPSession.emit (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:247:14)
    at Connection._onClose (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:128:21)
    at WebSocket.<anonymous> (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/WebSocketTransport.js:17:30)
    at WebSocket.onClose (/Users/gaelmetais/Documents/GitHub/phantomas/node_modules/ws/lib/event-target.js:129:16)
    at WebSocket.emit (events.js:314:20)
```

Not every time though. Sometimes I have another error `Error: HTTP response code from <https://www.airfrance.fr/> is 403`.
Code 403 means "forbidden", which is strange because it is a perfectly public website.

Here is a script to reproduce the error:
```js
const phantomas = require('./lib/index');
const promise = phantomas('https://www.airfrance.fr/', {
    'analyze-css': true
});
promise.
    then(results => {
        console.log('Metrics', results.getMetrics());
        console.log('Offenders', results.getAllOffenders());
    }).
    catch(res => {
        console.error(res);
        console.log('Error code #%d', res.code);
        process.exit(res.code);
    });
```

**Comment by macbre** [comment]
Just tested with the latest `devel`:

```
2020-10-05T20:16:46.442Z phantomas:core Node.js: v12.18.4
2020-10-05T20:16:46.443Z phantomas:core phantomas: 2.0.0-alpha2
2020-10-05T20:16:46.443Z phantomas:core Puppeteer: preferred revision r800071
```

```
$ DEBUG=phantomas:network ./airfrance.js 
  phantomas:network Network.requestWillBeSent > GET https://www.airfrance.fr/ [other] +0ms
  phantomas:network Network.dataReceived: {"requestId":"93DA52095AACF8DBBC1692D719CC6F6F","timestamp":156404.286294,"dataLength":265,"encodedDataLength":0} +293ms
  phantomas:network loadingFinished: {"requestId":"93DA52095AACF8DBBC1692D719CC6F6F","timestamp":156404.225259,"encodedDataLength":1042,"shouldReportCorbBlocking":false} +2ms
  phantomas:network Network.loadingFinished < h2 403  https://www.airfrance.fr/ (1.0 kB fetched, 0.3 kB uncompressed) +1ms
Error: HTTP response code from <https://www.airfrance.fr/> is 403
    at /home/macbre/github/phantomas/lib/index.js:141:13
    at async Promise.all (index 0)
Error code #NaN
```

However, after using user agent different than the default one (for instance by providing `"phone": true` option to `phantomas`) I'm able to get the site loaded properly (user agent filtering in action?):

```
2020-10-05T20:14:46.168Z phantomas:network Network.loadingFinished < h2 200  https://mobile.airfrance.fr/FR/fr/local/home/home/HomePageAction.do (18.0 kB fetched, 56.0 kB uncompressed)
```

**Comment by gmetais** [comment]
Hmm... I see! Sorry for taking your time.

**Comment by macbre** [comment]
@gmetais , no bother 🙂
